import traceback

def log_error(err):
    print("ðŸ”¥ ERROR TRACEBACK ðŸ”¥")
    traceback.print_exc()
    print("------------------------------------------------------")
